version: '{build}'
branches:
  only:
  - master

image: Visual Studio 2015

configuration:
- Debug
- Release

before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
  - cmd: CollectArtifacts.bat %CONFIGURATION%

artifacts:
  - path: publish
    name: threplay_rpi
