version: '{build}'
branches:
  only:
    - master

image: Visual Studio 2015

configuration:
  - Release
environment:
  PYTHON: C:\Python35-x64
install:
  - cmd: >-
      %PYTHON%\python -m pip install -U pip

      %PYTHON%\python -m pip install -r ManualGenerator\requirements.txt

before_build:
  - cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
  - cmd: CollectArtifacts.bat %CONFIGURATION%

artifacts:
  - path: publish
    name: threplay_rpi
